/**
 * Builds the app from its meta: the JSON objects under `meta/`. Today it handles pages.
 *
 *   npm run gen:meta
 *
 * Every `meta/pages/<id>.json` becomes `src/generated/pages/<slug>-page.tsx` with a test next to it,
 * and `src/generated/routes.tsx` plus `src/generated/nav.ts` wire all pages into the router and the
 * main navigation. `src/generated/` belongs to this script: it is rewritten on every run, so hand
 * changes go into meta or into files outside it.
 *
 * Structure is checked here with zod. Props are not: the generated JSX passes them as attributes, so
 * `npm run typecheck` checks them against each component's own props type.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

import { z } from 'zod';

const ROOT = path.resolve(import.meta.dirname, '..');
const META = path.join(ROOT, 'meta');
const UI = path.join(ROOT, 'src', 'components', 'ui');
const OUT = path.join(ROOT, 'src', 'generated');

const CONTAINER_TYPES = ['page', 'table', 'form', 'panel'] as const;

const id = z
  .string()
  .regex(/^[a-z][a-z0-9-]*$/, 'lowercase letters, digits and dashes, e.g. employee-new');

const componentField = z.strictObject({
  type: z.string().regex(/^[a-z][a-z0-9-]*$/, 'a folder name from src/components/ui, e.g. button'),
  id,
  props: z.record(z.string(), z.unknown()).default({}),
});

// A container inside a page is referenced by type and id; its own meta lives in its own folder.
const containerRef = z.strictObject({ type: z.enum(CONTAINER_TYPES), id });

const field = z.union([containerRef, componentField]);

const pageSchema = z
  .strictObject({
    type: z.literal('page'),
    id,
    name: z.string().trim().min(1).max(60),
    fields: z.array(field).default([]),
  })
  .superRefine((page, ctx) => {
    const ids = page.fields.map((f) => f.id);
    for (const dup of ids.filter((x, i) => ids.indexOf(x) !== i)) {
      ctx.addIssue({ code: 'custom', message: `fields: id "${dup}" is used twice` });
    }
    if (slug(page.name) === '')
      ctx.addIssue({ code: 'custom', message: 'name must contain a letter or a digit' });
  });

type Page = z.infer<typeof pageSchema>;
type Field = z.infer<typeof field>;

/** "New employee" -> "new-employee": the URL of the page. */
function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function pascal(kebab: string): string {
  return kebab.replace(/(^|-)([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
}

/** Exported names of a component folder, read from its source. */
function exportsOf(type: string): string[] {
  const file = path.join(UI, type, `${type}.tsx`);
  if (!fs.existsSync(file)) return [];
  const src = fs.readFileSync(file, 'utf8');
  const names = new Set<string>();
  for (const m of src.matchAll(/export \{([^}]*)\}/g)) {
    for (const n of (m[1] ?? '').split(',')) {
      const name = n
        .trim()
        .split(/\s+as\s+/)
        .pop();
      if (name) names.add(name);
    }
  }
  for (const m of src.matchAll(/export (?:function|const) ([A-Za-z0-9_]+)/g)) names.add(m[1] ?? '');
  return [...names].filter(Boolean);
}

function jsxValue(value: unknown): string {
  if (typeof value === 'string') return JSON.stringify(value);
  return `{${JSON.stringify(value)}}`;
}

function jsxAttrs(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([k]) => k !== 'children')
    .map(([k, v]) => (v === true ? ` ${k}` : ` ${k}=${jsxValue(v)}`))
    .join('');
}

interface Rendered {
  jsx: string;
  imports: Map<string, string>; // component name -> module
}

function renderField(page: Page, f: Field, imports: Map<string, string>): string {
  if ((CONTAINER_TYPES as readonly string[]).includes(f.type)) {
    // Generated by a later step; until then the page shows where it goes.
    return `<section data-meta-id="${f.id}" aria-label="${f.type} ${f.id}" className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">${f.type} "${f.id}" is not generated yet</section>`;
  }
  const c = f as z.infer<typeof componentField>;
  const name = pascal(c.type);
  const exported = exportsOf(c.type);
  if (exported.length === 0)
    throw new Error(`${page.id}: field "${c.id}": no component "${c.type}" in src/components/ui`);
  if (!exported.includes(name)) {
    throw new Error(
      `${page.id}: field "${c.id}": src/components/ui/${c.type} exports ${exported.join(', ')}, not ${name}`,
    );
  }
  imports.set(name, `@/components/ui/${c.type}`);
  const children = c.props.children;
  const attrs = ` data-meta-id="${c.id}"${jsxAttrs(c.props)}`;
  if (children === undefined) return `<${name}${attrs} />`;
  return `<${name}${attrs}>${typeof children === 'string' ? children : `{${JSON.stringify(children)}}`}</${name}>`;
}

function renderPage(page: Page): Rendered {
  const imports = new Map<string, string>();
  const body = page.fields.map((f) => renderField(page, f, imports)).join('\n      ');
  const byModule = new Map<string, string[]>();
  for (const [name, mod] of imports) byModule.set(mod, [...(byModule.get(mod) ?? []), name]);
  const importLines = [...byModule.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([mod, names]) => `import { ${names.sort().join(', ')} } from '${mod}';`)
    .join('\n');
  const jsx = `${importLines ? `${importLines}\n\n` : ''}/** Generated from meta/pages/${page.id}.json by \`npm run gen:meta\`. Do not edit: change the meta. */
export function ${pascal(page.id)}Page() {
  return (
    <section className="space-y-4">
      <h1 className="text-2xl font-semibold">${page.name}</h1>
      ${body}
    </section>
  );
}
`;
  return { jsx, imports };
}

function renderPageTest(page: Page): string {
  const ids = page.fields.map((f) => f.id);
  return `import { screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import { renderApp } from '@/test/render';

describe('${pascal(page.id)}Page', () => {
  it('opens at /${slug(page.name)} with its heading and fields', () => {
    renderApp(['/${slug(page.name)}']);

    expect(screen.getByRole('heading', { name: '${page.name}' })).toBeInTheDocument();
    for (const id of ${JSON.stringify(ids)}) expect(screen.getByTestId(id)).toBeInTheDocument();
  });
});
`;
}

function renderRoutes(pages: Page[]): string {
  const imports = pages
    .map((p) => `import { ${pascal(p.id)}Page } from '@/generated/pages/${slug(p.name)}-page';`)
    .join('\n');
  const routes = pages
    .map((p) => `  { path: '${slug(p.name)}', Component: ${pascal(p.id)}Page },`)
    .join('\n');
  return `import type { RouteObject } from 'react-router';

${imports}${imports ? '\n\n' : ''}/** Generated by \`npm run gen:meta\` from meta/pages. Mounted under the root layout in src/app/router.tsx. */
export const generatedRoutes: RouteObject[] = [
${routes}${routes ? '\n' : ''}];
`;
}

function renderNav(pages: Page[]): string {
  const links = pages
    .map((p) => `  { to: '/${slug(p.name)}', label: '${p.name.replace(/'/g, "\\'")}' },`)
    .join('\n');
  return `/** Generated by \`npm run gen:meta\` from meta/pages. Rendered by src/app/root-layout.tsx after the hand-written links. */
export const generatedNav: { to: string; label: string }[] = [
${links}${links ? '\n' : ''}];
`;
}

function readPages(): Page[] {
  const dir = path.join(META, 'pages');
  if (!fs.existsSync(dir)) return [];
  const pages: Page[] = [];
  const errors: string[] = [];
  for (const file of fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()) {
    const rel = `meta/pages/${file}`;
    let raw: unknown;
    try {
      raw = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));
    } catch (error) {
      errors.push(`${rel}: ${String(error)}`);
      continue;
    }
    const parsed = pageSchema.safeParse(raw);
    if (!parsed.success) {
      for (const issue of parsed.error.issues)
        errors.push(`${rel}: ${issue.path.join('.') || '(root)'}: ${issue.message}`);
      continue;
    }
    if (parsed.data.id !== file.replace(/\.json$/, ''))
      errors.push(`${rel}: id "${parsed.data.id}" must equal the file name`);
    pages.push(parsed.data);
  }
  const slugs = pages.map((p) => slug(p.name));
  for (const dup of slugs.filter((x, i) => slugs.indexOf(x) !== i))
    errors.push(`two pages map to the URL /${dup}`);
  if (errors.length > 0) {
    console.error('invalid meta:');
    for (const e of errors) console.error(`  ${e}`);
    process.exit(1);
  }
  return pages;
}

function main(): void {
  const pages = readPages();
  const files = new Map<string, string>();
  try {
    for (const page of pages) {
      files.set(`src/generated/pages/${slug(page.name)}-page.tsx`, renderPage(page).jsx);
      files.set(`src/generated/pages/${slug(page.name)}-page.test.tsx`, renderPageTest(page));
    }
  } catch (error) {
    console.error(`invalid meta:\n  ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
  files.set('src/generated/routes.tsx', renderRoutes(pages));
  files.set('src/generated/nav.ts', renderNav(pages));

  // The folder is owned by this script: everything not produced this run disappears.
  fs.rmSync(OUT, { recursive: true, force: true });
  for (const [file, content] of files) {
    fs.mkdirSync(path.dirname(path.join(ROOT, file)), { recursive: true });
    fs.writeFileSync(path.join(ROOT, file), content);
  }
  execFileSync(path.join(ROOT, 'node_modules', '.bin', 'prettier'), ['--write', ...files.keys()], {
    cwd: ROOT,
    stdio: 'pipe',
  });

  console.log(`generated ${String(pages.length)} page${pages.length === 1 ? '' : 's'}:`);
  for (const p of pages) console.log(`  /${slug(p.name)}  ${p.name}  (meta/pages/${p.id}.json)`);
  console.log(
    '\nNext: `npm run verify`. Type errors in src/generated point at props that the component does not accept.',
  );
}

main();
